#!/bin/sh -e

case "$1" in
    (configure)
#    if test -z "$2"; then
	    add-shell /bin/zsh
	    add-shell /usr/bin/zsh
#    fi
    ;;
    (abort-upgrade|abort-remove|abort-deconfigure)
	exit 0
    ;;
    (*)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 0
    ;;
esac

if test -x /usr/bin/update-menus ; then update-menus ; fi

update-alternatives --remove zsh /usr/bin/zsh
update-alternatives --install /bin/zsh zsh /bin/zsh4 50 \
		--slave /usr/bin/zsh zsh-usrbin /bin/zsh4
update-alternatives --install /bin/rzsh rzsh /bin/zsh4 50 \
		--slave /usr/share/man/man1/rzsh.1.gz rzsh.1.gz /usr/share/man/man1/zsh.1.gz
update-alternatives --install /bin/ksh ksh /bin/zsh4 5 \
                    --slave /usr/bin/ksh usr.bin.ksh /bin/zsh4 \
                    --slave /usr/share/man/man1/ksh.1.gz ksh.1.gz /usr/share/man/man1/zsh.1.gz

mkdir -m2775 -p /usr/local/share/zsh/site-functions && chown root:staff \
               /usr/local/share/zsh/site-functions || true

exit 0
